server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nursery
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: user
      password: password
      roles: USER
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create